version: '3'
services:
  ember-tutorial:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "4200:4200"
    container_name: ember-js
    stdin_open: true
    volumes:
       - ./:/app
       - /node_modules